# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gini's mean difference
#' 
#' Calculates Gini's mean difference of a given vector \code{x}.
#' 
#' @param x numeric vector.
#' 
#' @return A numeric value.
#' 
#' @examples
#' x <- rnorm(100)
#' GMD(x)
#' 
#' @export
GMD <- function(x) {
    .Call('_SChangeBlock_GMD', PACKAGE = 'SChangeBlock', x)
}

#' Mu
#' 
#' This function returns a vector of the block means for a given random field X.
#' 
#' @param X Numeric vector or matrix.
#' @param l block length. Numeric vector of the same length as X has dimensions.
#' 
#' @return A numeric vector.
#' 
#' @export
Mu <- function(X, l) {
    .Call('_SChangeBlock_Mu', PACKAGE = 'SChangeBlock', X, l)
}

#' Dependency Matrix Theta
#' 
#' This function generates a symmetric dependency matrix \eqn{\Theta} of a 
#' specific type of spatial MA(q) model.
#' 
#' @param q model order (integer).
#' @param param MA parameter (numeric value between 0 and 1).
#' 
#' @return A matrix of size (2q + 1) x (2q + 1).
#' 
#' @details Symmetric spatial MA(q) model with parameter \code{param} \eqn{= \theta}:
#'          \deqn{Y_{ij} = \sum_{k = -q}^q \sum_{l = -q}^q \theta^{|k - q - 1| + |l - q - 1|} \varepsilon_{kl}.}
#'          \eqn{\{\theta^{|k - q - 1| + |l - q - 1|}\}_{kl} = \Theta}.
#'          
#' @examples
#' genTheta(1, 0.2)
#' 
#' @export
genTheta <- function(q, param) {
    .Call('_SChangeBlock_genTheta', PACKAGE = 'SChangeBlock', q, param)
}

dependencyMA <- function(E, Theta_ = NULL, q_ = NULL, param_ = NULL) {
    .Call('_SChangeBlock_dependencyMA', PACKAGE = 'SChangeBlock', E, Theta_, q_, param_)
}

#' @export
gamma <- function(X, h1, h2) {
    .Call('_SChangeBlock_gamma', PACKAGE = 'SChangeBlock', X, h1, h2)
}

#' Long run variance
#' 
#' Estimates the long run variance of a 2-dimensional matrix \code{X} using kernel
#' density estimation and the Tukey-Hanning kernel function.
#' 
#' @param X numeric matrix,
#' @param b numeric vector containing exactly two values: the bandwidths for the row- reps. column-wise estimation.
#' 
#' @details ??????? Tukey-Hanning kernel ????????
#' 
#' @return A numeric value.
#' 
#' @examples
#' X1 <- genField(c(50, 50), Phi = genPhi(1, 0.4))
#' b <- lrvBandwidth(X1, 1/3, 2/3)
#' lrv(X1, b)
#' 
#' Phi <- matrix(c(0.08, 0.1, 0.08, 0.8, 1, 0.8, 0.08, 0.1, 0.08), ncol = 3)
#' X2 <- genField(c(50, 50), Phi = Phi)
#' b <- lrvBandwidth(X2, 1/3, 2/3)
#' lrv(X2, b)
#' 
#' @export
lrv <- function(X, b = 1L) {
    .Call('_SChangeBlock_lrv', PACKAGE = 'SChangeBlock', X, b)
}

#' Autocorrelation matrix
#' 
#' @param X numeric matrix,
#' @param b numeric vector containing exactly two values: the bandwidths for the row- reps. column-wise estimation. 
#' 
#' @export
autocov <- function(X, b, direction = 0L) {
    .Call('_SChangeBlock_autocov', PACKAGE = 'SChangeBlock', X, b, direction)
}

#' Optimal sizes ..................
#' 
#' ................................
#' 
#' @param n integer value.
#' @param lower,upper lower and upper search border, between 0 and 1.
#' @param step size of the step for the search, between 0 and 1.
#' 
#' @details
#' ........
#' 
#' @return A data frame containing
#' \item{n}{the given sample size}
#' \item{s}{the exponent in question}
#' \item{ln}{the resulting block length}
#' \item{bn}{the corresponding number of block}
#' \item{ln.bn}{block length times number of blocks}
#' \item{diff}{difference between the given sample size and the number of observations covered by the blocks}
#' 
#' @examples
#' sSizes(50)
#' sSizes(50, 0.6, 0.8, 0.01)
#' 
#' @export
sSizes <- function(n, lower = 0.5, upper = 1, step = 0.1) {
    .Call('_SChangeBlock_sSizes', PACKAGE = 'SChangeBlock', n, lower, upper, step)
}

#' Optimal parameter s
#' 
#' Calculates the best parameter for a given approximation s.
#' 
#' @param n Sample size(s), numeric (vector).
#' @param s Desired exponent, \eqn{0.5 \leq s \leq 1}.
#' 
#' @return Numeric Vector of the optimal exponents.
#' 
#' @export
sOpt <- function(n, s = 0.6) {
    .Call('_SChangeBlock_sOpt', PACKAGE = 'SChangeBlock', n, s)
}

